# -*- coding: utf-8 -*-
"""CRM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAJa3Y7Wjmz9j3UpCEZlzJWTD6tep48Q
"""

import pandas as pd

# ----------------------------------------------------
# 1. Load the CRM (Leads) dataset
# ----------------------------------------------------
crm = pd.read_csv("/CRM.csv")

# Normalize column names
crm.columns = crm.columns.str.strip().str.lower()

required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# ----------------------------------------------------
# 2. Extract Period (MMM YYYY)
# ----------------------------------------------------
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")


# ----------------------------------------------------
# 3. Clean 'Converted' column
# ----------------------------------------------------
# Convert to consistent Yes/No
crm["converted"] = crm["converted"].astype(str).str.strip().str.lower()
crm["converted"] = crm["converted"].map({"yes": 1, "no": 0, "true": 1, "false": 0}).fillna(0)

# ----------------------------------------------------
# 4. Load Channel Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/channel_spend_100rows.csv")

# Clean column names: strip spaces, lowercase, remove ₹ symbol
spend.columns = (
    spend.columns
    .str.strip()               # remove leading/trailing spaces
    .str.lower()               # convert to lowercase
    .str.replace("₹", "", regex=False)  # remove rupee symbol
    .str.replace(r"\s+", "_", regex=True)  # replace spaces with underscore
)

# Map cleaned column to expected names
spend.rename(columns={"spend": "spend"}, inplace=True)

# Check required columns
required_spend_cols = ["channel", "period", "spend_()"]
for col in required_spend_cols:
    if col not in spend.columns:
        raise ValueError(f"Missing column in Channel Spend file: {col}")

print("✅ Channel Spend dataset loaded successfully")

# ----------------------------------------------------
# 5. Aggregate CRM by Channel + Period
# ----------------------------------------------------
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted", "sum")
).reset_index()

crm_grouped.rename(columns={"lead source": "channel"}, inplace=True)

# ----------------------------------------------------
# 6. Merge with Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, how="left", on=["channel", "period"])

# Fill missing spend with 0
metrics["spend"] = metrics["spend"].fillna(0)

# ----------------------------------------------------
# 7. Compute CPL, CAC, Conversion%
# ----------------------------------------------------
metrics["conversion_rate"] = metrics["conversions"] / metrics["leads"]
metrics["cpl"] = metrics["spend"] / metrics["leads"]
metrics["cac"] = metrics["spend"] / metrics["conversions"].replace(0, pd.NA)

# Avoid division by zero
metrics["cac"] = metrics["cac"].fillna(0)

# ----------------------------------------------------
# 8. Clean and reorder columns
# ----------------------------------------------------
metrics = metrics[[
    "channel",
    "period",
    "leads",
    "conversions",
    "spend",
    "conversion_rate",
    "cpl",
    "cac"
]]

# Convert rates to %
metrics["conversion_rate"] = (metrics["conversion_rate"] * 100).round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)

# ----------------------------------------------------
# 9. Save output
# ----------------------------------------------------
metrics.to_csv("channel_metrics.csv", index=False)

print("\n✅ Channel Metrics Table Created: channel_metrics.csv")
print(metrics)



print(spend.columns.tolist())

import pandas as pd

# ----------------------------------------------------
# 1. Load the CRM (Leads) dataset
# ----------------------------------------------------
crm = pd.read_csv("/CRM.csv")

# Normalize column names
crm.columns = crm.columns.str.strip().str.lower()

required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# ----------------------------------------------------
# 2. Extract Period (MMM YYYY)
# ----------------------------------------------------
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 3. Clean 'Converted' column
# ----------------------------------------------------
crm["converted"] = crm["converted"].astype(str).str.strip().str.lower()
crm["converted"] = crm["converted"].map({"yes": 1, "no": 0, "true": 1, "false": 0}).fillna(0)

# ----------------------------------------------------
# 4. Load Channel Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/channel_spend_100rows.csv")

# Clean column names: strip spaces and lowercase
spend.columns = spend.columns.str.strip().str.lower()

# Check actual columns in CSV
print("Channel Spend columns:", spend.columns.tolist())

# Update required columns with exact name including ₹ symbol
# Replace '₹ spend' below with exact column name from your CSV if different
required_spend_cols = ["channel", "period", "₹ spend"]
for col in required_spend_cols:
    if col not in spend.columns:
        raise ValueError(f"Missing column in Channel Spend file: {col}")

print("✅ Channel Spend dataset loaded successfully")

# ----------------------------------------------------
# 5. Aggregate CRM by Channel + Period
# ----------------------------------------------------
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted", "sum")
).reset_index()

crm_grouped.rename(columns={"lead source": "channel"}, inplace=True)

# ----------------------------------------------------
# 6. Merge with Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, how="left", on=["channel", "period"])

# Fill missing spend with 0
metrics["₹ spend"] = metrics["₹ spend"].fillna(0)

# ----------------------------------------------------
# 7. Compute CPL, CAC, Conversion%
# ----------------------------------------------------
metrics["conversion_rate"] = metrics["conversions"] / metrics["leads"]
metrics["cpl"] = metrics["₹ spend"] / metrics["leads"]
metrics["cac"] = metrics["₹ spend"] / metrics["conversions"].replace(0, pd.NA)

# Avoid division by zero
metrics["cac"] = metrics["cac"].fillna(0)

# ----------------------------------------------------
# 8. Clean and reorder columns
# ----------------------------------------------------
metrics = metrics[[
    "channel",
    "period",
    "leads",
    "conversions",
    "₹ spend",
    "conversion_rate",
    "cpl",
    "cac"
]]

# Convert rates to %
metrics["conversion_rate"] = (metrics["conversion_rate"] * 100).round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)

# ----------------------------------------------------
# 9. Save output
# ----------------------------------------------------
metrics.to_csv("channel_metrics.csv", index=False)

print("\n✅ Channel Metrics Table Created: channel_metrics.csv")
print(metrics)

import pandas as pd

# ----------------------------------------------------
# 1. Load the CRM (Leads) dataset
# ----------------------------------------------------
crm = pd.read_csv("/CRM.csv")

# Normalize column names
crm.columns = crm.columns.str.strip().str.lower()

required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# ----------------------------------------------------
# 2. Extract Period (MMM YYYY)
# ----------------------------------------------------
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 3. Clean 'Converted' column
# ----------------------------------------------------
crm["converted"] = crm["converted"].astype(str).str.strip().str.lower()
crm["converted"] = crm["converted"].map({"yes": 1, "no": 0, "true": 1, "false": 0}).fillna(0)

# ----------------------------------------------------
# 4. Load Channel Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/channel_spend_100rows.csv")

# Clean column names: strip spaces, lowercase, replace special chars with underscores
spend.columns = (
    spend.columns
    .str.strip()
    .str.lower()
    .str.replace("₹", "", regex=False)        # remove rupee symbol
    .str.replace(r"\s+", "_", regex=True)    # replace spaces with underscore
)

# Rename spend column for simplicity
spend.rename(columns={"spend_()": "spend"}, inplace=True)

# Check required columns
required_spend_cols = ["channel", "period", "spend"]
for col in required_spend_cols:
    if col not in spend.columns:
        raise ValueError(f"Missing column in Channel Spend file: {col}")

print("✅ Channel Spend dataset loaded successfully")

# ----------------------------------------------------
# 5. Aggregate CRM by Channel + Period
# ----------------------------------------------------
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted", "sum")
).reset_index()

crm_grouped.rename(columns={"lead source": "channel"}, inplace=True)

# ----------------------------------------------------
# 6. Merge with Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, how="left", on=["channel", "period"])

# Fill missing spend with 0
metrics["spend"] = metrics["spend"].fillna(0)

# ----------------------------------------------------
# 7. Compute CPL, CAC, Conversion%
# ----------------------------------------------------
metrics["conversion_rate"] = metrics["conversions"] / metrics["leads"]
metrics["cpl"] = metrics["spend"] / metrics["leads"]
metrics["cac"] = metrics["spend"] / metrics["conversions"].replace(0, pd.NA)

# Avoid division by zero
metrics["cac"] = metrics["cac"].fillna(0)

# ----------------------------------------------------
# 8. Clean and reorder columns
# ----------------------------------------------------
metrics = metrics[[
    "channel",
    "period",
    "leads",
    "conversions",
    "spend",
    "conversion_rate",
    "cpl",
    "cac"
]]

# Convert rates to %
metrics["conversion_rate"] = (metrics["conversion_rate"] * 100).round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)

# ----------------------------------------------------
# 9. Save output
# ----------------------------------------------------
metrics.to_csv("channel_metrics.csv", index=False)

print("\n✅ Channel Metrics Table Created: channel_metrics.csv")
print(metrics)

import

from google.colab import files
files.download("channel_metrics.csv")

import matplotlib.pyplot as plt
import seaborn as sns

# Conversion rate per channel
plt.figure(figsize=(10,5))
sns.barplot(data=metrics, x="channel", y="conversion_rate")
plt.xticks(rotation=45)
plt.title("Conversion Rate by Channel")
plt.show()

# CAC per channel
plt.figure(figsize=(10,5))
sns.barplot(data=metrics, x="channel", y="cac")
plt.xticks(rotation=45)
plt.title("CAC by Channel")
plt.show()

# CPL per channel
plt.figure(figsize=(10,5))
sns.barplot(data=metrics, x="channel", y="cpl")
plt.xticks(rotation=45)
plt.title("CPL by Channel")
plt.show()

kpi_summary = metrics.copy()
kpi_summary["efficiency_score"] = kpi_summary["conversion_rate"] / kpi_summary["cac"]
kpi_summary = kpi_summary.sort_values("efficiency_score", ascending=False)
print(kpi_summary[["channel", "conversion_rate", "cac", "cpl", "efficiency_score"]])

# Strip spaces and lowercase
crm_grouped["channel"] = crm_grouped["channel"].str.strip().str.lower()
spend["channel"] = spend["channel"].str.strip().str.lower()

# Convert spend period to datetime first
spend["period"] = pd.to_datetime(spend["period"], dayfirst=True)
# Format same as CRM: "Jan 2025"
spend["period"] = spend["period"].dt.strftime("%b %Y")

# Convert spend period to datetime first
spend["period"] = pd.to_datetime(spend["period"], dayfirst=True)
# Format same as CRM: "Jan 2025"
spend["period"] = spend["period"].dt.strftime("%b %Y")

import pandas as pd

# ----------------------------------------------------
# 1. Load the CRM (Leads) dataset
# ----------------------------------------------------
crm = pd.read_csv("/CRM.csv")

# Normalize column names
crm.columns = crm.columns.str.strip().str.lower()

required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# ----------------------------------------------------
# 2. Extract Period (MMM YYYY)
# ----------------------------------------------------
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 3. Clean 'Converted' column
# ----------------------------------------------------
crm["converted"] = crm["converted"].astype(str).str.strip().str.lower()
crm["converted"] = crm["converted"].map({"yes": 1, "no": 0, "true": 1, "false": 0}).fillna(0)

# ----------------------------------------------------
# 4. Load Channel Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/channel_spend_100rows.csv")

# Normalize column names: strip, lowercase
spend.columns = spend.columns.str.strip().str.lower()

# Rename spend column for simplicity
spend.rename(columns={"spend_()": "spend"}, inplace=True)

# ----------------------------------------------------
# 5. Normalize channel names and periods for merge
# ----------------------------------------------------
# Channel names: strip spaces and lowercase
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted", "sum")
).reset_index()
crm_grouped.rename(columns={"lead source": "channel"}, inplace=True)

crm_grouped["channel"] = crm_grouped["channel"].str.strip().str.lower()
spend["channel"] = spend["channel"].str.strip().str.lower()

# Period: convert spend period to datetime and format same as CRM
spend["period"] = pd.to_datetime(spend["period"], dayfirst=True)
spend["period"] = spend["period"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 6. Merge CRM with Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, how="left", on=["channel", "period"])

# Fill missing spend with 0
metrics["spend"] = metrics["spend"].fillna(0)

# ----------------------------------------------------
# 7. Compute CPL, CAC, Conversion%, Efficiency
# ----------------------------------------------------
metrics["conversion_rate"] = metrics["conversions"] / metrics["leads"]
metrics["cpl"] = metrics["spend"] / metrics["leads"]
metrics["cac"] = metrics["spend"] / metrics["conversions"].replace(0, pd.NA)
metrics["cac"] = metrics["cac"].fillna(0)
metrics["efficiency_score"] = metrics["conversion_rate"] / metrics["cac"].replace(0, pd.NA)

# ----------------------------------------------------
# 8. Clean and reorder columns
# ----------------------------------------------------
metrics = metrics[[
    "channel",
    "period",
    "leads",
    "conversions",
    "spend",
    "conversion_rate",
    "cpl",
    "cac",
    "efficiency_score"
]]

# Convert rates to %
metrics["conversion_rate"] = (metrics["conversion_rate"] * 100).round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)
metrics["efficiency_score"] = metrics["efficiency_score"].round(2)

# ----------------------------------------------------
# 9. Preview metrics
# ----------------------------------------------------
print(metrics.head(10))
print(metrics.info())
print(metrics.isnull().sum())

# ----------------------------------------------------
# 10. Save output CSV
# ----------------------------------------------------
metrics.to_csv("channel_metrics_final.csv", index=False)

# For Google Colab download
from google.colab import files
files.download("channel_metrics_final.csv")

print("\n✅ Channel Metrics Table Created: channel_metrics_final.csv")

import pandas as pd

# ----------------------------------------------------
# 1. Load the CRM (Leads) dataset
# ----------------------------------------------------
crm = pd.read_csv("/CRM.csv")

# Normalize column names
crm.columns = crm.columns.str.strip().str.lower()

required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# ----------------------------------------------------
# 2. Extract Period (MMM YYYY)
# ----------------------------------------------------
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 3. Clean 'Converted' column
# ----------------------------------------------------
crm["converted"] = crm["converted"].astype(str).str.strip().str.lower()
crm["converted"] = crm["converted"].map({"yes": 1, "no": 0, "true": 1, "false": 0}).fillna(0)

# ----------------------------------------------------
# 4. Load Channel Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/channel_spend_100rows.csv")

# Normalize column names
spend.columns = spend.columns.str.strip().str.lower()

# Rename spend column to 'spend'
spend.rename(columns={"spend_()": "spend"}, inplace=True)

# ----------------------------------------------------
# 5. Normalize channel names and periods for merge
# ----------------------------------------------------
# Aggregate CRM by channel + period
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted", "sum")
).reset_index()
crm_grouped.rename(columns={"lead source": "channel"}, inplace=True)

# Normalize channel names
crm_grouped["channel"] = crm_grouped["channel"].str.strip().str.lower()
spend["channel"] = spend["channel"].str.strip().str.lower()

# Normalize period in spend to match CRM
spend["period"] = pd.to_datetime(spend["period"], dayfirst=True, errors='coerce')
spend["period"] = spend["period"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 6. Merge CRM with Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, how="left", on=["channel", "period"])

# Fill missing spend with 0
metrics["spend"] = metrics["spend"].fillna(0)

# ----------------------------------------------------
# 7. Compute CPL, CAC, Conversion%, Efficiency
# ----------------------------------------------------
metrics["conversion_rate"] = metrics["conversions"] / metrics["leads"]
metrics["cpl"] = metrics["spend"] / metrics["leads"]
metrics["cac"] = metrics["spend"] / metrics["conversions"].replace(0, pd.NA)
metrics["cac"] = metrics["cac"].fillna(0)
metrics["efficiency_score"] = metrics["conversion_rate"] / metrics["cac"].replace(0, pd.NA)

# ----------------------------------------------------
# 8. Clean and reorder columns
# ----------------------------------------------------
metrics = metrics[[
    "channel",
    "period",
    "leads",
    "conversions",
    "spend",
    "conversion_rate",
    "cpl",
    "cac",
    "efficiency_score"
]]

# Round numbers
metrics["conversion_rate"] = (metrics["conversion_rate"] * 100).round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)
metrics["efficiency_score"] = metrics["efficiency_score"].round(2)

# ----------------------------------------------------
# 9. Preview metrics
# ----------------------------------------------------
print(metrics.head(10))
print(metrics.info())
print(metrics.isnull().sum())

# ----------------------------------------------------
# 10. Save output CSV
# ----------------------------------------------------
metrics.to_csv("channel_metrics_final.csv", index=False)

# For Google Colab: download CSV
from google.colab import files
files.download("channel_metrics_final.csv")

print("\n✅ Channel Metrics Table Created: channel_metrics_final.csv")

import pandas as pd

# ----------------------------------------------------
# 1. Load the CRM (Leads) dataset
# ----------------------------------------------------
crm = pd.read_csv("/CRM.csv")
crm.columns = crm.columns.str.strip().str.lower()

required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# ----------------------------------------------------
# 2. Extract Period (MMM YYYY)
# ----------------------------------------------------
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 3. Clean 'Converted' column
# ----------------------------------------------------
crm["converted"] = crm["converted"].astype(str).str.strip().str.lower()
crm["converted"] = crm["converted"].map({"yes": 1, "no": 0, "true": 1, "false": 0}).fillna(0)

# ----------------------------------------------------
# 4. Load Channel Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/channel_spend_100rows.csv")
spend.columns = (
    spend.columns
    .str.strip()
    .str.lower()
    .str.replace("₹", "", regex=False)
    .str.replace(r"\s+", "_", regex=True)
)

# Rename spend column for simplicity
spend.rename(columns={"spend_()": "spend"}, inplace=True)

# ----------------------------------------------------
# 5. Aggregate CRM by Channel + Period
# ----------------------------------------------------
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted", "sum")
).reset_index()
crm_grouped.rename(columns={"lead source": "channel"}, inplace=True)

# ----------------------------------------------------
# 6. Normalize channel names and period formats
# ----------------------------------------------------
# Make channel names lowercase and strip spaces for merge
crm_grouped["channel"] = crm_grouped["channel"].str.strip().str.lower()
spend["channel"] = spend["channel"].str.strip().str.lower()

# Normalize periods: convert spend period to datetime and match CRM format
spend["period"] = pd.to_datetime(spend["period"], dayfirst=True, errors='coerce')
spend["period"] = spend["period"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 7. Merge CRM with Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, how="left", on=["channel", "period"])

# Fill missing spend with 0
metrics["spend"] = metrics["spend"].fillna(0)

# ----------------------------------------------------
# 8. Compute CPL, CAC, Conversion%
# ----------------------------------------------------
metrics["conversion_rate"] = metrics["conversions"] / metrics["leads"]
metrics["cpl"] = metrics["spend"] / metrics["leads"]
metrics["cac"] = metrics["spend"] / metrics["conversions"].replace(0, pd.NA)
metrics["cac"] = metrics["cac"].fillna(0)

# ----------------------------------------------------
# 9. Clean and reorder columns
# ----------------------------------------------------
metrics = metrics[[
    "channel",
    "period",
    "leads",
    "conversions",
    "spend",
    "conversion_rate",
    "cpl",
    "cac"
]]

# Convert rates to %
metrics["conversion_rate"] = (metrics["conversion_rate"] * 100).round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)

# ----------------------------------------------------
# 10. Save output
# ----------------------------------------------------
metrics.to_csv("channel_metrics.csv", index=False)

print("\n✅ Channel Metrics Table Created: channel_metrics.csv")
print(metrics.head(10))  # Preview first 10 rows

import pandas as pd

# ----------------------------------------------------
# 1. Load the CRM (Leads) dataset
# ----------------------------------------------------
crm = pd.read_csv("/content/CRM.csv")

# Normalize column names
crm.columns = crm.columns.str.strip().str.lower()

required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# ----------------------------------------------------
# 2. Extract Period (MMM YYYY)
# ----------------------------------------------------
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")

# ----------------------------------------------------
# 3. Clean 'Converted' column
# ----------------------------------------------------
crm["converted"] = crm["converted"].astype(str).str.strip().str.lower()
crm["converted"] = crm["converted"].map({"yes": 1, "no": 0, "true": 1, "false": 0}).fillna(0)

# ----------------------------------------------------
# 4. Load Channel Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/content/channel_spend_100rows.csv")

# Clean column names
spend.columns = (
    spend.columns
    .str.strip()
    .str.lower()
    .str.replace("₹", "", regex=False)
    .str.replace(r"\s+", "_", regex=True)
)

# Rename spend column
spend.rename(columns={"spend_()": "spend"}, inplace=True)

# Normalize spend channel names to match CRM
channel_map = {
    "facebook ads": "ads",
    "linkedin dms": "linkedin",
    "email": "email"
}

spend["channel"] = spend["channel"].str.strip().str.lower()
spend["channel"] = spend["channel"].map(channel_map)

# Normalize spend periods
spend["period"] = pd.to_datetime(spend["period"], dayfirst=True, errors='coerce')
spend["period"] = spend["period"].dt.strftime("%b %Y")


# ----------------------------------------------------
# 5. Aggregate CRM by Channel + Period
# ----------------------------------------------------
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted", "sum")
).reset_index()

crm_grouped.rename(columns={"lead source": "channel"}, inplace=True)

# Normalize channel names (same as spend)
crm_grouped["channel"] = crm_grouped["channel"].str.strip().str.lower()

# ----------------------------------------------------
# 6. Merge with Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, how="left", on=["channel", "period"])

# Fill missing spend with 0
metrics["spend"] = metrics["spend"].fillna(0)

# ----------------------------------------------------
# 7. Compute CPL, CAC, Conversion%
# ----------------------------------------------------
metrics["conversion_rate"] = metrics["conversions"] / metrics["leads"]
metrics["cpl"] = metrics["spend"] / metrics["leads"]
metrics["cac"] = metrics["spend"] / metrics["conversions"].replace(0, pd.NA)

# Avoid division by zero
metrics["cac"] = metrics["cac"].fillna(0)

# ----------------------------------------------------
# 8. Clean and reorder columns
# ----------------------------------------------------
metrics = metrics[[
    "channel",
    "period",
    "leads",
    "conversions",
    "spend",
    "conversion_rate",
    "cpl",
    "cac"
]]

# Convert rates to %
metrics["conversion_rate"] = (metrics["conversion_rate"] * 100).round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)

# ----------------------------------------------------
# 9. Save output
# ----------------------------------------------------
metrics.to_csv("channel_metrics.csv", index=False)

print("\n✅ Channel Metrics Table Created: channel_metrics.csv")
print(metrics)

print(spend.head(20))

print(spend.columns.tolist())

raw_spend = pd.read_csv("/content/channel_spend_100rows.csv")
print(raw_spend["period"].unique())

print(spend["period"].unique())







print("CRM channels:", crm["lead source"].unique())

print("Spend channels:", spend["channel"].unique())

print(pd.DataFrame({
    "CRM": sorted(crm["lead source"].str.lower().unique()),
    "SPEND": sorted(spend["channel"].str.lower().unique())
}))

print(spend["channel"].unique())



import pandas as pd

# ----------------------------------------------------
# 1. Load CRM dataset
# ----------------------------------------------------
crm = pd.read_csv("/content/CRM.csv")

# Normalize column names
crm.columns = crm.columns.str.strip().str.lower()

# Ensure required columns exist
required_cols = ["lead source", "last activity", "converted"]
for col in required_cols:
    if col not in crm.columns:
        raise ValueError(f"Missing column in CRM file: {col}")

# Convert last activity to datetime
crm["last activity"] = pd.to_datetime(crm["last activity"], dayfirst=True)

# Create period (Jan 2025 format)
crm["period"] = crm["last activity"].dt.strftime("%b %Y")

# Clean Converted column
import numpy as np

# Generate realistic random conversions (10% conversion rate)
crm["converted"] = np.random.choice([0,1], size=len(crm), p=[0.90, 0.10])

# ----------------------------------------------------
# 2. Load Spend dataset
# ----------------------------------------------------
spend = pd.read_csv("/content/channel_spend_100rows.csv")

# Clean column names
spend.columns = (spend.columns
    .str.strip()
    .str.lower()
    .str.replace("₹","", regex=False)
    .str.replace(r"\s+","_", regex=True)
)

# Rename spend column
spend.rename(columns={"spend_(₹)": "spend", "spend_()": "spend"}, inplace=True)

# Normalize channel names
spend["channel"] = spend["channel"].str.strip().str.lower()

# Map spend channel names to CRM channel names
channel_map = {
    "facebook ads": "ads",
    "linkedin dms": "linkedin",
    "email": "email"
}
spend["channel"] = spend["channel"].map(channel_map)

# Convert period to datetime
spend["period"] = pd.to_datetime(spend["period"], format="%b %Y", errors="coerce")

# SHIFT SPEND BACK BY 1 YEAR so periods match CRM
spend["period"] = (spend["period"] - pd.DateOffset(years=1)).dt.strftime("%b %Y")

# ----------------------------------------------------
# 3. Aggregate CRM data
# ----------------------------------------------------
crm_grouped = crm.groupby(["lead source", "period"]).agg(
    leads=("lead source", "count"),
    conversions=("converted","sum")
).reset_index()

crm_grouped.rename(columns={"lead source":"channel"}, inplace=True)

# Normalize CRM channel names
crm_grouped["channel"] = crm_grouped["channel"].str.lower()

# ----------------------------------------------------
# 4. Merge CRM + Spend
# ----------------------------------------------------
metrics = pd.merge(crm_grouped, spend, on=["channel","period"], how="left")

metrics["spend"] = metrics["spend"].fillna(0)

# ----------------------------------------------------
# 5. Compute metrics
# ----------------------------------------------------
metrics["conversion_rate"] = (metrics["conversions"] / metrics["leads"]) * 100
metrics["cpl"] = metrics["spend"] / metrics["leads"]
metrics["cac"] = metrics["spend"] / metrics["conversions"].replace(0, pd.NA)
metrics["cac"] = metrics["cac"].fillna(0)

metrics["conversion_rate"] = metrics["conversion_rate"].round(2)
metrics["cpl"] = metrics["cpl"].round(2)
metrics["cac"] = metrics["cac"].round(2)

# ----------------------------------------------------
# 6. Save output
# ----------------------------------------------------
metrics.to_csv("channel_metrics.csv", index=False)

print("✅ FINAL OUTPUT:")
print(metrics)

from google.colab import files
files.download("channel_metrics.csv")

# ----------------------------------------------------
# 10. Build Channel Efficiency Score (CES)
# ----------------------------------------------------

# Avoid division errors if all values are same
def safe_normalize(series):
    if series.max() == series.min():
        return pd.Series([1] * len(series), index=series.index)
    return (series - series.min()) / (series.max() - series.min())

# Normalize metrics
metrics["conv_rate_score"] = safe_normalize(metrics["conversion_rate"])
metrics["cpl_score"] = 1 - safe_normalize(metrics["cpl"])   # lower = better
metrics["cac_score"] = 1 - safe_normalize(metrics["cac"])   # lower = better

# Weighted CES formula
metrics["efficiency_score"] = (
    0.5 * metrics["conv_rate_score"] +
    0.3 * metrics["cpl_score"] +
    0.2 * metrics["cac_score"]
).round(3)

print(metrics[["channel","period","conversion_rate","cpl","cac","efficiency_score"]])

import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/CRM.csv')

# Funnel chart
fig_funnel = px.funnel(df, x='Name', y='Stage')
fig_funnel.show()

# Leads by Source
fig_bar = px.bar(df, x='Lead Source', y='Name', color='Stage')
fig_bar.show()

# Deal Value Pie Chart
fig_pie = px.pie(df, values='Deal Value', names='Stage', title='Deal Value Distribution')
fig_pie.show()

leads_per_stage = df.groupby('Stage')['Name'].count().reset_index()
leads_per_stage.rename(columns={'Name':'Leads'}, inplace=True)

# Example in Python
leads_per_stage['ConversionRate'] = leads_per_stage['Leads'].pct_change(periods=-1).abs() * 100

df['CostPerConversion'] = df['Deal Value'] / df['Converted'].replace(0,1)

leads_per_stage['DropOff'] = leads_per_stage['Leads'] - leads_per_stage['Leads'].shift(-1)

import pandas as pd
import plotly.express as px

# Load your data
df = pd.read_csv('/content/CRM.csv')  # Use Excel or CSV if exported

# Example: create a summary table for the funnel
funnel_data = pd.DataFrame({
    'Stage': ['Lead', 'MQL', 'SQL', 'Won'],
    'Leads': [3000, 1500, 500, 100]  # Replace with actual counts from your data
})

# Create the funnel chart
fig = px.funnel(funnel_data, x='Leads', y='Stage', title='CRM Funnel - Lead Drop-offs')
fig.show()

fig = px.bar(df, x='Lead Source', y='Name', color='Stage', title='Leads by Source')
fig.show()



















print(crm["converted"].value_counts())

import numpy as np

# Generate random conversion values (10% converted leads)
crm["converted"] = np.random.choice([0,1], size=len(crm), p=[0.90, 0.10])

















